#! /bin/sh
compton -b --config ~/.config/compton/compton.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          50

bspc config split_ratio          0.52
bspc config auto_alternate       true
bspc config auto_cancel 	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc rule -a Chromium desktop='^2'

xrandr --output eDP1 --mode 2048x1152 &
tint2 &
nm-applet &
thunar --daemon &
wal -i ~/Pictures/nasa/ &
razer-service &
redshift-gtk &
